lib/tist_web/router.ex
defmodule TistWeb.Router do
  use TistWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Tist.Authorization.Pipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug Guardian.Plug.EnsureAuthenticated
    plug Guardian.Plug.LoadResource
  end

  pipeline :only_admin do
    plug Guardian.Permissions.Bitwise, ensure: %{admin: [:approve_users]}
  end

  scope "/", TistWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", TistWeb.Authorization, as: :authorization do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", TistWeb.Authorization, as: :authorization do
    pipe_through [:browser, :authenticated]

    resources "/sessions", SessionController, only: [:delete]
  end


  scope "/admin", TistWeb.Admin, as: :admin do
    pipe_through [:browser, :authenticated, :only_admin]

    resources "/users", UserController, only: ~w(index create update delete)a
  end

  scope "/registration", TistWeb.Registration, as: :registration do
    pipe_through :browser

    get   "/new", UserController, :new
    post  "/",    UserController, :create
  end

  scope "/twilight_imperium", TistWeb.TwilightImperium, as: :twilight_imperium do
    pipe_through [:browser, :authenticated]

    resources "/games", GameController do
      resources "/scores", ScoreController, except: ~w(index show)a
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", TistWeb do
  #   pipe_through :api
  # end
end

lib/tist_web/views/layout_view.ex
defmodule TistWeb.LayoutView do
  use TistWeb, :view
end

lib/tist_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tist!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <%= if authenticated?(@conn) do %>
              <li><%= link "Your Games", to: twilight_imperium_game_path(@conn, :index) %></li>
              <li><%= link "Statistics", to: "/" %></li>
              <li><%= link "Logout", to: authorization_session_path(@conn, :delete, current_user(@conn)), method: "delete" %></li>
            <% else %>
              <li><%= link "Login", to: authorization_session_path(@conn, :new) %></li>
              <li><%= link "Create Account", to: registration_user_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>