lib/tist_web/router.ex
defmodule TistWeb.Router do
  use TistWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Tist.Authorization.Pipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug Guardian.Plug.EnsureAuthenticated
    plug Guardian.Plug.LoadResource
  end

  pipeline :only_admin do
    plug Guardian.Permissions.Bitwise, ensure: %{admin: [:approve_users]}
  end

  scope "/", TistWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", TistWeb.Authorization, as: :authorization do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", TistWeb.Authorization, as: :authorization do
    pipe_through [:browser, :authenticated]

    resources "/sessions", SessionController, only: [:delete]
  end


  scope "/admin", TistWeb.Admin, as: :admin do
    pipe_through [:browser, :authenticated, :only_admin]

    resources "/users", UserController, only: ~w(index create update delete)a
  end

  scope "/registration", TistWeb.Registration, as: :registration do
    pipe_through :browser

    get   "/new", UserController, :new
    post  "/",    UserController, :create
  end

  scope "/twilight_imperium", TistWeb.TwilightImperium, as: :twilight_imperium do
    pipe_through [:browser, :authenticated]

    resources "/games", GameController do
      resources "/scores", ScoreController, except: ~w(index show)a
    end
  end
  # Other scopes may use custom stacks.
  # scope "/api", TistWeb do
  #   pipe_through :api
  # end
end

lib/tist/twilight_imperium/faction.ex
defmodule Tist.TwilightImperium.Faction do
  use Ecto.Schema

  alias Tist.TwilightImperium.{Game, Score}

  schema "factions" do
    has_many :wins,   Game, foreign_key: :winning_faction_id
    has_many :scores, Score

    field :name, :string

    timestamps()
  end
end

lib/tist/twilight_imperium/game.ex
defmodule Tist.TwilightImperium.Game do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query

  alias Tist.TwilightImperium
  alias Tist.TwilightImperium.{Faction,Game,Score}

  schema "games" do
    belongs_to  :winning_faction, Faction
    belongs_to  :user,            Tist.Authorization.User
    has_many    :scores,          Score

    field :played_on,     :date
    field :player_count,  :integer
    field :turns,         :integer

    timestamps()
  end

  @doc false
  def changeset(%Game{} = game, attrs) do
    game
    |> cast(attrs, ~w(played_on player_count turns winning_faction_id)a)
    |> foreign_key_constraint(:winning_faction_id)
    |> validate_required(~w(played_on turns)a)
    |> validate_inclusion(:player_count, 3..6)
  end

  @doc false
  def owned_by(query \\ Game, user_id) do
    query
    |> where([g], g.user_id == ^user_id)
  end

end

lib/tist/twilight_imperium/score.ex
defmodule Tist.TwilightImperium.Score do
  use Ecto.Schema
  import Ecto.Changeset

  alias Tist.TwilightImperium
  alias Tist.TwilightImperium.{Faction, Game, Score}

  schema "scores" do
    belongs_to  :faction, Faction
    belongs_to  :game,    Game

    field :score, :integer

    timestamps()
  end

  def changeset(%Score{} = score, attrs) do
    score
    |> cast(attrs, ~w(faction_id score)a)
    |> foreign_key_constraint(:faction_id)
    |> validate_required(:score)
  end
end

lib/tist/twilight_imperium/statistic.ex
defmodule Tist.TwilightImperium.Statistic do
  use Ecto.Schema

  @primary_key false

  # This is a materialized view, so no insertion of records please.
  schema "statistics_mv" do
    field :faction,         :string
    field :games,           :integer
    field :score_per_turn,  :decimal
    field :wins,            :integer
  end
end

lib/tist/twilight_imperium/twilight_imperium.ex
defmodule Tist.TwilightImperium do
  @moduledoc """
  The TwilightImperium context.
  """

  import Ecto.Query, warn: false
  alias Tist.Repo

  alias Tist.TwilightImperium.{Faction, Game, Score, Statistic}

  @doc """
  Returns the list of twilight_imperium_games.

  ## Examples

      iex> list_twilight_imperium_games()
      [%Game{}, ...]

  """
  def list_twilight_imperium_games(user_id) do
    Game
    |> Game.owned_by(user_id)
    |> Repo.all()
    |> Repo.preload(:winning_faction)
  end

  @doc """
  Returns a list of statistics.

  ## Example

    iex> list_statistics()
    [%Statistic{}]

  """
  def list_statistics do
    Statistic
    |> order_by(asc: :faction)
    |> Repo.all()
  end

  @doc """
  Gets a single game.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_game!(1,123,:scores)
      %Game{}

      iex> get_game!(1,456,:scores)
      ** (Ecto.NoResultsError)

  """
  def get_game!(user_id, id, preloads \\ []) do
    Game
    |> Game.owned_by(user_id)
    |> Repo.get!(id)
    |> Repo.preload(preloads)
    #|> (&Enum.reduce(preloads, &1, &Repo.preload/2)).()
  end

  def get_game!(user_id), do: %Game{user_id: user_id}

  @doc """
  Gets a single score.

  Raises `Ecto.NoResultsError` if the Game does not exist.

  ## Examples

      iex> get_score(game,123)
      %Game{}

      iex> get_score(game,456)
      ** (Ecto.NoResultsError)
  """
  def get_score!(game, id) do
    game
    |> Ecto.assoc(:scores)
    |> Repo.get!(id)
  end

  def get_score!(game), do: %Score{game_id: game.id}

  @doc """
  Creates a game.

  ## Examples

      iex> create_game(%{field: value})
      {:ok, %Game{}}

      iex> create_game(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_game(user_id, attrs \\ %{}) do
    %Game{user_id: user_id}
    |> Game.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Creates a score.

  ## Examples

      iex> create_score(%{field: value})
      {:ok, %Score{}}

      iex> create_score(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_score(game, attrs \\ %{}) do
    game
    |> Ecto.build_assoc(:scores)
    |> Score.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a game.

  ## Examples

      iex> update_game(game, %{field: new_value})
      {:ok, %Game{}}

      iex> update_game(game, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_game(%Game{} = game, attrs) do
    game
    |> Game.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Updates a score.

  ## Examples

      iex> update_score(score, %{field: new_value})
      {:ok, %Score{}}

      iex> update_score(score, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_score(%Score{} = score, attrs) do
    score
    |> Score.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Game.

  ## Examples

      iex> delete_game(game)
      {:ok, %Game{}}

      iex> delete_game(game)
      {:error, %Ecto.Changeset{}}

  """
  def delete_game(%Game{} = game) do
    Repo.delete(game)
  end

  @doc """
  Deletes a Score.

  ## Examples

      iex> delete_score(score)
      {:ok, %Score{}}

      iex> delete_score(score)
      {:error, %Ecto.Changeset{}}
  """
  def delete_score(%Score{} = score) do
    Repo.delete(score)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking game changes.

  ## Examples

      iex> change_game(game)
      %Ecto.Changeset{source: %Game{}}

  """
  def change_game(%Game{} = game) do
    Game.changeset(game, %{})
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking score changes.

  ## Examples

      iex> change_score(score)
      %Ecto.Changeset{source: %Score{}}

  """
  def change_score(%Score{} = score) do
    Score.changeset(score, %{})
  end

  @doc """
  Returns a list of factions for a select form element.

  ## Examples

    iex> faction_collection()
    %Map{['faction', 1]}

  """
  def faction_collection do
    Faction
    |> order_by(asc: :name)
    |> Repo.all()
    |> Enum.map(&{&1.name, &1.id})
    |> Enum.into([{"", nil}])
  end
end

lib/tist_web/controllers/twilight_imperium/game_controller.ex
defmodule TistWeb.TwilightImperium.GameController do
  use TistWeb, :controller

  alias Tist.TwilightImperium
  alias Tist.TwilightImperium.Game

  def index(conn, _params) do
    twilight_imperium_games = TwilightImperium.list_twilight_imperium_games(current_user(conn).id)
    render(conn, "index.html", twilight_imperium_games: twilight_imperium_games)
  end

  def new(conn, _params) do
    changeset = TwilightImperium.change_game(TwilightImperium.get_game!(current_user(conn).id))

    conn
    |> assign(:changeset, changeset)
    |> assign(:factions, TwilightImperium.faction_collection)
    |> render("new.html")
  end

  def create(conn, %{"game" => game_params}) do
    case TwilightImperium.create_game(current_user(conn).id, game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game created successfully.")
        |> redirect(to: twilight_imperium_game_path(conn, :show, game))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> assign(:factions, TwilightImperium.faction_collection)
        |> render("new.html")
    end
  end

  def show(conn, %{"id" => id}) do
    game = TwilightImperium.get_game!(current_user(conn).id, id, [:winning_faction, scores: :faction])
    render(conn, "show.html", game: game)
  end

  def edit(conn, %{"id" => id}) do
    game = TwilightImperium.get_game!(current_user(conn).id, id)
    changeset = TwilightImperium.change_game(game)

    conn
    |> assign(:changeset, TwilightImperium.change_game(game))
    |> assign(:factions,  TwilightImperium.faction_collection)
    |> assign(:game,      game)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "game" => game_params}) do
    game = TwilightImperium.get_game!(current_user(conn).id, id)

    case TwilightImperium.update_game(game, game_params) do
      {:ok, game} ->
        conn
        |> put_flash(:info, "Game updated successfully.")
        |> redirect(to: twilight_imperium_game_path(conn, :show, game))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> assign(:factions,  TwilightImperium.faction_collection)
        |> assign(:game,      game)
        |> render("edit.html")
    end
  end

  def delete(conn, %{"id" => id}) do
    game = TwilightImperium.get_game!(current_user(conn).id, id)
    {:ok, _game} = TwilightImperium.delete_game(game)

    conn
    |> put_flash(:info, "Game deleted successfully.")
    |> redirect(to: twilight_imperium_game_path(conn, :index))
  end
end

lib/tist_web/controllers/twilight_imperium/score_controller.ex
defmodule TistWeb.TwilightImperium.ScoreController do
  use TistWeb, :controller

  alias Tist.TwilightImperium
  alias Tist.TwilightImperium.Game

  def new(conn, _params, game) do
    changeset = game
      |> TwilightImperium.get_score!
      |> TwilightImperium.change_score

    conn
    |> assign(:changeset, changeset)
    |> assign(:game,      game)
    |> assign(:factions,  TwilightImperium.faction_collection)
    |> render("new.html")
  end

  def create(conn, %{"score" => score_params}, game) do
    case TwilightImperium.create_score(game, score_params) do
      {:ok, score} ->
        conn
        |> put_flash(:info, "Game created successfully.")
        |> redirect(to: twilight_imperium_game_path(conn, :show, game))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> assign(:game,      game)
        |> assign(:factions, TwilightImperium.faction_collection)
        |> render("new.html")
    end
  end

  def edit(conn, %{"id" => id}, game) do
    score = TwilightImperium.get_score!(game, id)

    conn
    |> assign(:changeset, TwilightImperium.change_score(score))
    |> assign(:factions,  TwilightImperium.faction_collection)
    |> assign(:game,      game)
    |> assign(:score,     score)
    |> render("edit.html")
  end

  def update(conn, %{"id" => id, "score" => score_params}, game) do
    score = TwilightImperium.get_score!(game, id)

    case TwilightImperium.update_score(score, score_params) do
      {:ok, score} ->
        conn
        |> put_flash(:info, "Game updated successfully.")
        |> redirect(to: twilight_imperium_game_path(conn, :show, game))
      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> assign(:factions,  TwilightImperium.faction_collection)
        |> assign(:game,      game)
        |> assign(:score,     score)
        |> render("edit.html")
    end
  end

  def delete(conn, %{"id" => id}, game) do
    score = TwilightImperium.get_score!(game, id)
    {:ok, _score} = TwilightImperium.delete_score(score)

    conn
    |> put_flash(:info, "Game deleted successfully.")
    |> redirect(to: twilight_imperium_game_path(conn, :show, game))
  end

  def action(conn, _) do
    game = conn
      |> current_user_id()
      |> TwilightImperium.get_game!(conn.params["game_id"])

    apply(__MODULE__, action_name(conn), [conn, conn.params, game])
  end
end

lib/tist_web/views/twilight_imperium/game_view.ex
defmodule TistWeb.TwilightImperium.GameView do
  use TistWeb, :view
end

lib/tist_web/views/twilight_imperium/score_view.ex
defmodule TistWeb.TwilightImperium.ScoreView do
  use TistWeb, :view
end

lib/tist_web/templates/twilight_imperium/game/edit.html.eex
<h2>Edit Game</h2>

<%= render "form.html", Map.put(assigns, :action, twilight_imperium_game_path(@conn, :update, @game)) %>

<ul class="nav nav-pills">
  <li><%= link "Back", to: twilight_imperium_game_path(@conn, :index) %></li>
</ul>

lib/tist_web/templates/twilight_imperium/game/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f,        :played_on, class: "control-label" %>
    <%= date_select f,  :played_on, class: "form-control" %>
    <%= error_tag f,    :played_on %>
  </div>

  <div class="form-group">
    <%= label f,        :player_count, "Number of Players", class: "control-label" %>
    <%= number_input f, :player_count, class: "form-control" %>
    <%= error_tag f,    :player_count %>
  </div>

  <div class="form-group">
    <%= label f,        :turns, "Number of Turns", class: "control-label" %>
    <%= number_input f, :turns, class: "form-control" %>
    <%= error_tag f,    :turns %>
  </div>

  <div class="form-group">
    <%= label f,      :winning_faction_id, class: "control-label" %>
    <%= select f,     :winning_faction_id, @factions, class: "form-control" %>
    <%= error_tag f,  :winning_faction_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tist_web/templates/twilight_imperium/game/index.html.eex
<h2>Games</h2>

<table class="table">
  <thead>
    <tr>
      <th>Played On</th>
      <th>Players</th>
      <th>Turns</th>
      <th>Winner</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for game <- @twilight_imperium_games do %>
    <tr>
      <td><%= game.played_on %></td>
      <td><%= game.player_count %></td>
      <td><%= game.turns %></td>
      <td><%= game.winning_faction.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: twilight_imperium_game_path(@conn, :show, game), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: twilight_imperium_game_path(@conn, :edit, game), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: twilight_imperium_game_path(@conn, :delete, game), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<ul class="nav nav-pills">
  <li><%= link "New Game", to: twilight_imperium_game_path(@conn, :new) %></li>
</ul>

lib/tist_web/templates/twilight_imperium/game/new.html.eex
<h2>New Game</h2>

<%= render "form.html", Map.put(assigns, :action, twilight_imperium_game_path(@conn, :create)) %>

<ul class="nav nav-pills">
  <li><%= link "Back", to: twilight_imperium_game_path(@conn, :index) %></li>
</ul>

lib/tist_web/templates/twilight_imperium/game/show.html.eex
<h2>Show Game</h2>

<dl>
  <dt>Played On</dt>          <dd><%= @game.played_on %></dd>
  <dt>Number of Players</dt>  <dd><%= @game.player_count %></dd>
  <dt>Number of Turns</dt>    <dd><%= @game.turns %></dd>
  <dt>Winning Faction</dt>    <dd><%= @game.winning_faction.name %></dd>
</dl>

<%= if Enum.count(@game.scores) > 0 do %>
  <h3>Victory Point Scores</h3>
  <table class="table">
    <thead>
      <th>Faction</th>
      <th>Victory Points</th>
      <th></th>
    </thead>
    <tbody>
      <%= for score <- @game.scores do %>
        <tr>
          <td><%= score.faction.name %></td>
          <td><%= score.score %></td>

          <td class="text-right">
            <span><%= link "Edit",    to: twilight_imperium_game_score_path(@conn, :edit,   @game, score), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Delete",  to: twilight_imperium_game_score_path(@conn, :delete, @game, score), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<ul class="nav nav-pills">
  <li><%= link "Edit",                    to: twilight_imperium_game_path(@conn, :edit, @game) %></li>
  <li><%= link "Add Victory Point Score", to: twilight_imperium_game_score_path(@conn, :new, @game) %></li>
  <li><%= link "Back",                    to: twilight_imperium_game_path(@conn, :index) %></li>
</ul>